### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by jaysaleh** [jaysaleh/my-portfolio#5]
- [x] Header
- [x] Mexico Trip
- [x] Cliff Jumping almost dying
- [x] 3D printed rocket launch
- [x] Footer

**Comment by billie-cat** [comment]
I think this issue and potential others I am not cc'd on.

**Comment by billie-cat** [comment]
I just subscribed myself. Can you add Fola as well?

**Comment by jaysaleh** [comment]
I can try assigning Fola to it but I'm not sure if that is the same as her subscribing

**Comment by billie-cat** [comment]
I believe to subscribe us you need to write @billie-cat and @f-camp 

Typically the assignee is who is working on it, so you should be the only one assigned.

**Comment by jaysaleh** [comment]
@billie-cat @f-camp
