### ISSUE TITLE
" active" space being unclear

### ISSUE THREAD

**Issue by jaysaleh** [jaysaleh/my-portfolio#8]
- [x] Create a const string called ADD_ATTRIBUTE and then SHOW_DOT: ADD_ATTRIBUTE + 'active'

_Originally posted by @billie-cat in https://github.com/jaysaleh/my-portfolio/pull/4/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjc3NjE4MjM5OnYy/unresolve_

**Comment by billie-cat** [comment]
I also think this issue was not necessary. It is only necessary if you add a TODO and will not fix it in the pull request out for review.
